# Generated by Django 4.2.2 on 2023-08-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helloKitti", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentlikes",
            old_name="likedat",
            new_name="liked_at",
        ),
        migrations.RenameField(
            model_name="commentlikes",
            old_name="post_id",
            new_name="user_id",
        ),
        migrations.DeleteModel(
            name="Likes",
        ),
    ]
