# Generated by Django 4.2.2 on 2023-08-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helloKitti", "0003_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="created_at",
            new_name="commented_at",
        ),
    ]
